apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: role1
  namespace: role-binding
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
