apiVersion: apps/v1
kind: DaemonSet
metadata:
  generation: 3
  name: ds1
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: app1
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: app1
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: gs
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker-node-2
