apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: it-deploy
  name: it-deploy
  namespace: it
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: it-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: it-app
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-home-page
      volumes:
      - configMap:
          name: it-cm
        name: nginx-home-page
