apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: po-on-ssd-node
  name: po-on-ssd-node
spec:
  containers:
  - image: nginx
    name: po-on-ssd-node
  nodeSelector:
    disktype: ssd
