apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: memory-demo
  name: memory-demo
  namespace: cpu-memory
spec:
  resources:
    requests:
      memory: "100Mi"
    limits:
      memory: "200Mi"
  containers:
  - image: nginx
    name: memory-demo
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang","1"]
