apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mc1
  name: mc1
  namespace: mc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mc1
    spec:
      containers:
      - image: httpd
        name: httpd
        ports:
        - containerPort: 80
      - image: busybox
        name: busybox
        command: ["/bin/sh"]
        args: ["-c", "sleep 12345"]

