apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cm-volume-special-key
  name: cm-volume-special-key
  namespace: cm
spec:
  restartPolicy: Never
  volumes:
  - name: config-volume
    configMap:
      name: special-config
      items:
      - key: SPECIAL_LEVEL
        path: keys
  containers:
  - image: busybox
    name: cm-volume-special-key
    command:
    - sh
    - -c
    - " cat /etc/config/keys "
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
   
