apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: dapi-test-pod
  name: dapi-test-pod
spec:
  restartPolicy: Never
  containers:
  - image: busybox
    name: dapi-test-pod
    command:
    - sh
    - -c
    - "env"
    env:
    - name: SPECIAL_LEVEL_KEY
      valueFrom:
        configMapKeyRef:
          name: special-config
          key: special.how
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: env-config
          key: log_level
