kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-claim-local-storage
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 500Mi


