kind: Pod
apiVersion: v1
metadata:
  name: writer
spec:
  volumes:
  - name: cache
    emptyDir: {}
  containers:  
  - name: writer-app
    image: busybox
    command: ["sh","-c"," while true; do echo 'hello' > /cache/data; sleep 20; done;"]
    volumeMounts:
    - name: cache
      mountPath: /cache  

