apiVersion: v1
kind: Service
metadata:
  name: finance-service
  namespace: finance
spec:
  ports:
  - name: http-service
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: finance-app
  type: ClusterIP
