apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hr-deploy
  name: hr-deploy
  namespace: hr
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hr-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hr-app
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-home-page
        - mountPath: /tmp/hello
          name: test-hello-volume    
      volumes:
      - configMap:
          name: nginx-content
        name: nginx-home-page
      - name: test-hello-volume
        configMap:
          name: test-hello   
