apiVersion: v1
data:
  test.txt: |
    Hello Naresh
kind: ConfigMap
metadata:
  creationTimestamp: "2025-11-01T12:37:17Z"
  name: test-hello
  namespace: hr
  resourceVersion: "924613"
  uid: 4739177c-b84a-42f9-9ec3-bf437c87e633
