apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol-2
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Mi
  hostPath:
    path: /tmp/pv-vol-2
  persistentVolumeReclaimPolicy: Retain


  
