apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ready-if-service-ready
  name: ready-if-service-ready
spec:
  containers:
  - image: busybox
    imagePullPolicy: IfNotPresent
    name: busybox-app
    command: ['sh','-c','sleep 2000']
    livenessProbe:
      exec:
        command:
        - "true"
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      exec:
        command:
        - sh
        - -c
        - 'wget -T2 -O- http://service-i-am-ready:80'
      initialDelaySeconds: 5
      periodSeconds: 5  
