apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-test-deploy
  name: secret-test-deploy
  namespace: secret
spec:
  containers:
  - args:
    - sleep
    - "2000"
    image: busybox
    name: secret-test-deploy
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: secret-volume
      mountPath: /var/secret
  volumes:
  - name: secret-volume
    secret:
      secretName: tls-client-secret

