kind: Pod
apiVersion: v1
metadata:
  name: app1
  namespace: secret
spec:
  containers:
  - name: mysql-db
    image: mysql:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sc-2
          key: MYSQL_ROOT_PASSWORD
