apiVersion: v1
kind: Pod
metadata:
  labels:
    run: app2
  name: app2
  namespace: secret
spec:
  containers:
  - image: httpd
    name: app2
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sc-2
          key: MYSQL_ROOT_PASSWORD
