apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: ds1

spec:
  selector:
    matchLabels:
      name: app1
  template:
    metadata:
      labels:
        name: app1
    spec:
      containers:
      - name: gs
        image: nginx    
