apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llc1
  serviceName: nginx
  template:
    metadata:
      labels:
        app: llc1
    spec:
      containers:
        - name: bg
          image: nginx
          ports:
          - containerPort: 80
          volumeMounts:
          - name: vol1
            mountPath: /mnt
  volumeClaimTemplates:
  - metadata:
      name: vol1
    spec:
      resources:
        requests:
          storage: 1Gi
      accessModes: 
      - ReadWriteOnce 
