apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-dotfiles-pod
  name: secret-dotfiles-pod
  namespace: secret
spec:
  restartPolicy: Never
  volumes:
  - name: secret-volume
    secret:
      secretName: dotfile-secret
  containers:
  - image: busybox
    name: secret-dotfiles-pod
    command:
    - sh
    - -c
    - " echo 'i am ready'; sleep 1d"
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: /etc/secret-volume
        
