apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    test: liveness
  name: liveness
spec:
  containers:
  - image: busybox:1.27.2
    name: liveness
    command:
    - sh
    - -c
    - "touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600"
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5

