apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: liveness-http
  name: liveness-http
  namespace: liveness
spec:
  containers:
  - image: registry.k8s.io/e2e-test-images/agnhost:2.40
    name: liveness-http
    args:
    - liveness
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
