apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-b
  name: pod-b
spec:
  containers:
  - image: busybox
    name: pod-b
    command:
    - sh
    - -c
    - "ready; sleep 1d"
    livenessProbe:
      exec:
        command:
        - sh
        - -c
        - wget -T2 -O- http://pod-a-svc.liveness.svc.cluster.local:80
      failureThreshold: 30
      periodSeconds: 10
      
