apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: logger
  name: logger
spec:
  volumes:
  - name: log
    emptyDir: {}
  containers:
  - image: busybox
    name: c1
    command:
    - sh
    - -c
    - | 
      while true; do
        echo $(date) >> /var/log/date.log;
        sleep 1;
        done
    volumeMounts:
    - name: log
      mountPath: /var/log

  initContainers:
  - image: busybox
    name: c2
    restartPolicy: Always
    command:
    - sh
    - -c
    - |
      while [ ! -f /var/log/date.log ];
       do echo 'waiting'; sleep 1;
       done;
       tail -f /var/log/date.log;
       sleep 1
       
    volumeMounts:
    - name: log
      mountPath: /var/log
