apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-step
  name: multi-step
spec:
  volumes:
  - name: work
    emptyDir: {} 
  initContainers:
  - image: busybox
    name: step-1
    command:
    - sh
    - -c
    - "echo 'step1' >> /work/step1.txt"
    volumeMounts:
    - name: work
      mountPath: /work
  - image: busybox
    name: step-2
    command:
    - sh
    - -c
    - "echo 'step2' >> /work/step1.txt"
    volumeMounts:
    - name: work
      mountPath: /work
  - image: busybox
    name: step-3
    command:
    - sh
    - -c
    - "echo 'step3' >> /work/step1.txt"
    volumeMounts:
    - name: work
      mountPath: /work
  containers:
  - image: busybox
    name: main
    command:
    - sh
    - -c
    - "cat /work/step1.txt; sleep 1d"
    volumeMounts:
    - name: work
      mountPath: /work
