apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: cj2
  namespace: dev-job
spec:
  jobTemplate:
    metadata:
      name: cj2
    spec:
      template:
        spec:
          containers:
          - command:
            - sleep
            - "20"
            image: httpd
            name: cj2
          restartPolicy: OnFailure
  schedule: '*/2 * * * *'
status: {}
