apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dc20
  name: dc20
  namespace: quota-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dc20
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dc20
    spec:
      containers:
      - image: httpd
        name: httpd
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
